### ISSUE TITLE
GraphQL request fails with "Type User has no field safeAddress"

### ISSUE THREAD

**Issue by GriffGreen** [CirclesUBI/circles-subgraph#23]
https://circles.garden/welcome/connect
<img width="966" alt="Screen Shot 2020-07-21 at 4 54 25 PM" src="https://user-images.githubusercontent.com/14945613/88070610-2a534800-cb73-11ea-9251-a0b38e01ecf3.png">
and when i tried to connect them it didnt work anyway :-(

**Comment by adzialocha** [comment]
This request seems to fail after changing to the new Graph endpoint @ana0:

`{ user(id: "0xce2e8538f0e3759b4a3b8676eef3a9ad331d7295") { safeAddress } }`
`{"errors":[{"locations":[{"line":1,"column":60}],"message":"Type User has no field safeAddress"}]}`
