### ISSUE TITLE
Subgraph fails to sync

### ISSUE THREAD

**Issue by llunaCreixent** [CirclesUBI/circles-subgraph#52]
The [circlesubi subgraph](https://thegraph.com/hosted-service/subgraph/circlesubi/circles) stopped syncing  on block 19,001,246. No errors in the logs.
Now when I try to deploy starting from block 12,529,458 it fails with these warnings: 
```
Unexpected RPC error, error: Transport("Unexpected response status code: 413 Payload Too Large"), component: BlockStream
Trying again after eth_getLogs RPC call failed (attempt #10) with result Err(Transport("Unexpected response status code: 413 Payload Too Large")), component: BlockStream.
```
The deployment works if I deploy from a few blocks before it failed, but the data from previous blocks is lost.

**Comment by llunaCreixent** [comment]
Some Questions:
- What is the version of the graph-node running on the Hosted Service? Is it the last released? v0.24.2?

**Comment by leoyvens** [comment]
The hosted service closely follows graph node master. We have had previous reports of "payload to large" https://github.com/graphprotocol/graph-node/issues/2616. I noticed that your subgraph is not updated to the latest graph-cli/-ts and to apiVersion 0.0.5, that might be unrelated to these issues but it is strongly recommended.

**Comment by llunaCreixent** [comment]
I updated `graph-cli/-ts` (see https://github.com/CirclesUBI/circles-subgraph/pull/53) to the latest and the subgraph it's not successfully synced in the Hosted Service (see: https://thegraph.com/hosted-service/subgraph/circlesubi/circles?selected=logs).

**Comment by leoyvens** [comment]
@llunaCreixent are you referring to the current or pending version?

**Comment by llunaCreixent** [comment]
I was referring to the pending version, it stopped after having 199 entities. Then, I deployed from a later block, and started syncing again. Then, I deployed from the first block where Circles txs exist. Although now it's syncing, we are not sure if it indexed the first txs, and from time to time we can see these warnings in the logs:
```
Trying again after eth_getBlockByNumber RPC call failed (attempt #15) with result Err(Transport error: Unexpected response status code: 502 Bad Gateway), component: BlockStream

```

**Comment by leoyvens** [comment]
@llunaCreixent We have rolled out batching of eth_getLogs, so the 413 errors should be fixed.

**Comment by llunaCreixent** [comment]
We updated the subgraph version and now this issue in not relevant anymore.
Thanks for your help @leoyvens !!
