### ISSUE TITLE
Inconsistency in Entity counts in subgraphs

### ISSUE THREAD

**Issue by llunaCreixent** [CirclesUBI/circles-subgraph#69]
Our subgraph finished syncing [1], however the Entitty count is slightly different from the subgraph azf20 deployed [2]. 
What can be the issue here? 
After removing the eth_calls [3], we only cleaned the unsued variables [4], but we don't expect this to affect the indexing.

c

[1] https://thegraph.com/hosted-service/subgraph/circlesubi/circles-ubi
[2] https://thegraph.com/hosted-service/subgraph/azf20/circles-ubi
[3] https://github.com/CirclesUBI/circles-subgraph/pull/63
[4] https://github.com/CirclesUBI/circles-subgraph/pull/65/files

4.4.2020
- compare with our graphnode once it is deployed.  

29.6.22
Comparison is done. Entity counts can be found in the Developer Diary. It can be seen that our subgraph has more entities that the other two subgraphs hosted in the `api.thegraph` so we are using our provisioned endoint from now onwards

**Comment by llunaCreixent** [comment]
Investigating with The Graph team

**Comment by llunaCreixent** [comment]
https://ipfs.io/ipfs/QmeGRED3nSeDUxvUPekr3tJc2bfm5zbcV2BQkQhHB3NosY that is the manifest for the subgraph [2]

**Comment by llunaCreixent** [comment]
We could also observe if there are differences too if we deploy Adam's subgraph for sokol.

**Comment by JacqueGM** [comment]
@llunaCreixent  since we decided to not use anymore the hosted service can we close this ticket?

**Comment by llunaCreixent** [comment]
I think the ticket is still relevant, and we can move forward it once we can deploy several subgraphs in our instance.

**Comment by llunaCreixent** [comment]
Right now, the subgraph `v1.4.0` deployed in the Hosted Service has the same EntityCount as our self-hosted. This is good and suggests that the Hosted Service database is not corrupted as before.

Request to check:
```
curl --location --request POST 'https://api.thegraph.com/index-node/graphql'  --data-raw '{"query":"{indexingStatusForCurrentVersion(subgraphName: \"circlesubi/circles-ubi\") { synced health entityCount fatalError { message block { number hash } handler } chains { chainHeadBlock { number } latestBlock { number } } } }"}'
```

We still have to compare with different versions of subgraphs.

**Comment by JacqueGM** [comment]
Closing this ticket since both subgraphs are synced from the last two versions @llunaCreixent
