### ISSUE TITLE
Reduce time for installing dependencies

### ISSUE THREAD

**Issue by llunaCreixent** [CirclesUBI/circles-subgraph#81]

**Comment by JacqueGM** [comment]
@juanenrisley isnt this achieved with your latest update? version 2.1.0

**Comment by juanenrisley** [comment]
> @juanenrisley isnt this achieved with your latest update? version 2.1.0

Yes, it is. Now the times are reduced by far thanks to node 16 and the use of the docker image.

**Comment by JacqueGM** [comment]
awesome, closing this ticket then!
